export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_SINGLE_USERS = "FETCH_SINGLE_USERS";
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
